"""Per-domain speaker maps for :mod:`storyline.audio.sentence_audio`.

These are the single source of truth for default voice resolution.
Upstream code builds a ``speaker_map`` dict by combining entries from
these maps with any per-episode overrides (e.g. podcast character voices).

Conventions
-----------
- speaker_id 0 → Chinese voice (zh-first speaker)
- speaker_id 1 → English voice (en-first speaker)
- speaker_id 2+ → episode-specific characters

Voice reference audio is paired with ``-ref.txt`` files containing just
the reference transcript (one line).  Character voice-design profiles
use ``.txt`` files with structured key=value fields.
"""

import re
from pathlib import Path

from storyline.audio.sentence_audio import VoiceSpec

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_VOICES_DIR = _PROJECT_ROOT / "voices"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_ref_text(stem: str) -> str:
    """Read reference text from voices/{stem}-ref.txt (single line)."""
    path = _VOICES_DIR / f"{stem}-ref.txt"
    return path.read_text(encoding="utf-8").strip()


def _read_profile_dialogue(path: Path) -> str:
    """Extract ``dialogue`` field from a structured voice profile file.

    Used for episode-specific character voices generated by voice-design.
    """
    content = Path(path).read_text(encoding="utf-8")
    for line in content.splitlines():
        m = re.match(r'^dialogue\s*=\s*"(.+)"\s*$', line.strip())
        if m:
            return m.group(1)
    raise ValueError(f"No dialogue field in voice profile: {path}")


# =============================================================================
# Book: voice clone only (ann / scott)
# =============================================================================


BOOK_SPEAKERS: dict[int, VoiceSpec] = {
    0: VoiceSpec(
        mode="clone",
        ref_audio=str(_VOICES_DIR / "ann-short.mp3"),
        ref_text=_read_ref_text("ann-short"),
    ),
    1: VoiceSpec(
        mode="clone",
        ref_audio=str(_VOICES_DIR / "scott-short.mp3"),
        ref_text=_read_ref_text("scott-short"),
    ),
}


# =============================================================================
# Podcast: builtin and clone
# =============================================================================

_PODCAST_HOST_BUILTIN: dict[int, VoiceSpec] = {
    0: VoiceSpec(mode="builtin", speaker="Serena"),   # teacher (zh)
    1: VoiceSpec(mode="builtin", speaker="Ryan"),      # student (en)
}


def _podcast_clone_map() -> dict[int, VoiceSpec]:
    return {
        0: VoiceSpec(
            mode="clone",
            ref_audio=str(_VOICES_DIR / "teacher.wav"),
            ref_text=_read_ref_text("teacher"),
        ),
        1: VoiceSpec(
            mode="clone",
            ref_audio=str(_VOICES_DIR / "student.wav"),
            ref_text=_read_ref_text("student"),
        ),
    }


def podcast_speakers(*, builtin: bool = False) -> dict[int, VoiceSpec]:
    """Return the default podcast speaker map.

    *builtin*=True → Serena / Ryan; otherwise clone from voices/teacher and
    voices/student reference audio.
    """
    return dict(_PODCAST_HOST_BUILTIN) if builtin else _podcast_clone_map()


def resolve_character_speaker(slug: str, speaker_id: int) -> VoiceSpec:
    """Resolve a podcast character voice from voice-design output in voices/.

    Character voices are episode-specific and stored as
    ``voices/{slug}_{speaker_id}.wav`` + ``.txt``.
    """
    stem = slug.replace("-", "_") + f"_{speaker_id}"
    wav_path = _VOICES_DIR / f"{stem}.wav"
    txt_path = _VOICES_DIR / f"{stem}.txt"

    if not wav_path.exists() or not txt_path.exists():
        raise FileNotFoundError(
            f"Character voice not found for speaker {speaker_id} in {slug}. "
            f"Expected: {wav_path} and {txt_path}"
        )
    return VoiceSpec(
        mode="clone",
        ref_audio=str(wav_path),
        ref_text=_read_profile_dialogue(txt_path),
    )